mod error;
mod service;
mod ty;

pub use self::{
    error::DescriptorError,
    service::{MethodDescriptor, MethodDescriptorRef, ServiceDescriptor, ServiceDescriptorRef},
    ty::{
        Cardinality, EnumDescriptor, EnumDescriptorRef, EnumValueDescriptor,
        EnumValueDescriptorRef, ExtensionDescriptor, ExtensionDescriptorRef, FieldDescriptor,
        FieldDescriptorRef, Kind, KindRef, MessageDescriptor, MessageDescriptorRef,
        OneofDescriptor, OneofDescriptorRef,
    },
};

use std::{collections::HashMap, convert::TryInto, fmt, iter, ops::Range, sync::Arc};

use prost::{bytes::Buf, Message};
use prost_types::{FileDescriptorProto, FileDescriptorSet};

use self::service::ServiceDescriptorInner;

pub(crate) const MAP_ENTRY_KEY_NUMBER: u32 = 1;
pub(crate) const MAP_ENTRY_VALUE_NUMBER: u32 = 2;

/// A `DescriptorPool` is a collection of related descriptors. Typically it will be created from
/// a [`FileDescriptorSet`] output by the protobuf compiler (see [`DescriptorPool::from_file_descriptor_set`])
/// but it may also be built up manually by adding individual files.
///
/// Methods like [`MessageDescriptor::extensions`] will be scoped to just the files contained within the parent
/// `DescriptorPool`.
///
/// This type is uses reference counting internally so it is cheap to clone. Modifying an instance of a
/// pool will not update any existing clones of the instance.
#[derive(Clone, Default)]
pub struct DescriptorPool {
    inner: Arc<DescriptorPoolInner>,
}

/// A borrowed version of [`DescriptorPool``].
#[derive(Copy, Clone)]
pub struct DescriptorPoolRef<'a> {
    inner: &'a Arc<DescriptorPoolInner>,
}

#[derive(Clone, Default)]
struct DescriptorPoolInner {
    files: Vec<FileDescriptorInner>,
    file_names: HashMap<Box<str>, FileIndex>,
    type_map: ty::TypeMap,
    services: Vec<ServiceDescriptorInner>,
}

/// A single source file containing protobuf messages and services.
#[derive(Clone, PartialEq, Eq)]
pub struct FileDescriptor {
    pool: DescriptorPool,
    index: FileIndex,
}

#[doc(hidden)]
#[derive(Copy, Clone, PartialEq, Eq)]
pub struct FileDescriptorRef<'a> {
    pool: DescriptorPoolRef<'a>,
    index: FileIndex,
}

#[derive(Clone)]
struct FileDescriptorInner {
    raw: FileDescriptorProto,
    syntax: Syntax,
    services: Range<ServiceIndex>,
}

/// The syntax of a proto file.
#[derive(Copy, Clone, PartialEq, Eq, Hash)]
pub enum Syntax {
    /// The `proto2` syntax.
    Proto2,
    /// The `proto3` syntax.
    Proto3,
}

type FileIndex = u32;
type ServiceIndex = u32;
type MethodIndex = u32;
type MessageIndex = u32;
type OneofIndex = u32;
type ExtensionIndex = u32;
type EnumIndex = u32;
type EnumValueIndex = u32;

impl DescriptorPool {
    /// Creates a new, empty [`DescriptorPool`].
    ///
    /// For the common case of creating a `DescriptorPool` from a single [`FileDescriptorSet`], see
    /// [`DescriptorPool::from_file_descriptor_set`] or [`DescriptorPool::decode`].
    pub fn new() -> Self {
        DescriptorPool::default()
    }

    /// Gets a [`DescriptorPoolRef`] referencing this pool.
    pub fn as_ref(&self) -> DescriptorPoolRef<'_> {
        DescriptorPoolRef { inner: &self.inner }
    }

    /// Creates a [`DescriptorPool`] from a [`FileDescriptorSet`].
    ///
    /// This is equivalent to calling [`DescriptorPool::add_file_descriptor_set`] on an empty `DescriptorPool`
    /// instance. See that method's documentation for details.
    pub fn from_file_descriptor_set(
        file_descriptor_set: FileDescriptorSet,
    ) -> Result<Self, DescriptorError> {
        let mut pool = DescriptorPool::new();
        pool.add_file_descriptor_set(file_descriptor_set)?;
        Ok(pool)
    }

    /// Decodes a [`FileDescriptorSet`] from its protobuf byte representation and
    /// creates a new [`DescriptorPool`] wrapping it.
    pub fn decode<B>(bytes: B) -> Result<Self, DescriptorError>
    where
        B: Buf,
    {
        DescriptorPool::from_file_descriptor_set(
            FileDescriptorSet::decode(bytes)
                .map_err(DescriptorError::decode_file_descriptor_set)?,
        )
    }

    /// Adds a new [`FileDescriptorSet`] to this [`DescriptorPool`].
    ///
    /// A file descriptor set may be generated by running the protobuf compiler with the
    /// `--descriptor_set_out` flag. If you are using [`prost-build`](https://crates.io/crates/prost-build),
    /// then [`Config::file_descriptor_set_path`](https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method..file_descriptor_set_path)
    /// is a convenient way to generate it as part of your build.
    ///
    /// This method may return an error if `file_descriptor_set` is invalid, for example
    /// it contains references to types not in the set. If `file_descriptor_set` was created by
    /// the protobuf compiler, these error cases should never occur since it performs its own
    /// validation.
    pub fn add_file_descriptor_set(
        &mut self,
        file_descriptor_set: FileDescriptorSet,
    ) -> Result<(), DescriptorError> {
        self.add_file_descriptor_protos(file_descriptor_set.file)
    }

    /// Adds a collection of file descriptors to this pool.
    ///
    /// The file descriptors may be provided in any order, however all types referenced must be defined
    /// either in one of the files provided, or in a file previously added to the pool.
    ///
    /// Duplicate file descriptors are ignored, however adding two different files with the same name
    /// will return an error.
    pub fn add_file_descriptor_protos<I>(&mut self, files: I) -> Result<(), DescriptorError>
    where
        I: IntoIterator<Item = FileDescriptorProto>,
    {
        // Note we could use `Arc::make_mut` here but by always cloning we
        // avoid putting the pool into an inconsistent state on error.
        let mut inner = (*self.inner).clone();

        let file_indices = inner.build_files(files)?;
        let files = &mut inner.files;

        inner.type_map.add_files(
            file_indices
                .clone()
                .map(|file_index| (file_index, &files[file_index as usize])),
        )?;
        inner.type_map.shrink_to_fit();

        for file_index in file_indices {
            let file = &mut files[file_index as usize];
            let start: ServiceIndex = to_index(inner.services.len());
            for service in &file.raw.service {
                inner.services.push(ServiceDescriptorInner::from_raw(
                    &file.raw,
                    file_index,
                    service,
                    &inner.type_map,
                )?);
            }
            file.services = start..to_index(inner.services.len());
        }

        if let Some(old_inner) = Arc::get_mut(&mut self.inner) {
            *old_inner = inner;
        } else {
            self.inner = Arc::new(inner);
        }
        Ok(())
    }

    /// Add a single file descriptor to the pool.
    ///
    /// All types referenced by the file must be defined either in the file itself, or in a file
    /// previously added to the pool.
    pub fn add_file_descriptor_proto(
        &mut self,
        file: FileDescriptorProto,
    ) -> Result<(), DescriptorError> {
        self.add_file_descriptor_protos(iter::once(file))
    }

    /// Gets an iterator over the file descriptors added to this pool.
    pub fn files(&self) -> impl ExactSizeIterator<Item = FileDescriptor> + '_ {
        self.as_ref().files().map(FileDescriptorRef::to_owned)
    }

    /// Gets a file descriptor by its name, or `None` if no such file has been added.
    pub fn get_file_by_name(&self, name: &str) -> Option<FileDescriptor> {
        self.as_ref()
            .get_file_by_name(name)
            .map(FileDescriptorRef::to_owned)
    }

    /// Gets a iterator over the raw [`FileDescriptorProto`] instances wrapped by this [`DescriptorPool`].
    pub fn file_descriptor_protos(
        &self,
    ) -> impl ExactSizeIterator<Item = &FileDescriptorProto> + '_ {
        self.as_ref().file_descriptor_protos()
    }

    /// Gets an iterator over the services defined in these protobuf files.
    pub fn services(&self) -> impl ExactSizeIterator<Item = ServiceDescriptor> + '_ {
        self.as_ref().services().map(ServiceDescriptorRef::to_owned)
    }

    /// Gets an iterator over all message types defined in these protobuf files.
    ///
    /// The iterator includes nested messages defined in another message.
    pub fn all_messages(&self) -> impl ExactSizeIterator<Item = MessageDescriptor> + '_ {
        self.as_ref()
            .all_messages()
            .map(MessageDescriptorRef::to_owned)
    }

    /// Gets an iterator over all enum types defined in these protobuf files.
    ///
    /// The iterator includes nested enums defined in another message.
    pub fn all_enums(&self) -> impl ExactSizeIterator<Item = EnumDescriptor> + '_ {
        self.as_ref().all_enums().map(EnumDescriptorRef::to_owned)
    }

    /// Gets an iterator over all extension fields defined in these protobuf files.
    ///
    /// The iterator includes nested extension fields defined in another message.
    pub fn all_extensions(&self) -> impl ExactSizeIterator<Item = ExtensionDescriptor> + '_ {
        self.as_ref()
            .all_extensions()
            .map(ExtensionDescriptorRef::to_owned)
    }

    /// Gets a [`MessageDescriptor`] by its fully qualified name, for example `my.package.MessageName`.
    pub fn get_message_by_name(&self, name: &str) -> Option<MessageDescriptor> {
        self.as_ref()
            .get_message_by_name(name)
            .map(MessageDescriptorRef::to_owned)
    }

    /// Gets an [`EnumDescriptor`] by its fully qualified name, for example `my.package.EnumName`.
    pub fn get_enum_by_name(&self, name: &str) -> Option<EnumDescriptor> {
        self.as_ref()
            .get_enum_by_name(name)
            .map(EnumDescriptorRef::to_owned)
    }
}

impl<'a> DescriptorPoolRef<'a> {
    pub fn to_owned(self) -> DescriptorPool {
        DescriptorPool {
            inner: self.inner.to_owned(),
        }
    }

    pub fn files(&self) -> impl ExactSizeIterator<Item = FileDescriptorRef<'a>> + 'a {
        FileDescriptorRef::iter(*self)
    }

    pub fn get_file_by_name(&self, name: &str) -> Option<FileDescriptorRef<'a>> {
        self.inner
            .file_names
            .get(name)
            .map(|&index| FileDescriptorRef::new(*self, index as _))
    }

    pub fn file_descriptor_protos(
        &self,
    ) -> impl ExactSizeIterator<Item = &'a FileDescriptorProto> + 'a {
        self.inner.files.iter().map(|f| &f.raw)
    }

    pub fn services(&self) -> impl ExactSizeIterator<Item = ServiceDescriptorRef<'a>> + 'a {
        let this = *self;
        (0..self.inner.services.len()).map(move |index| ServiceDescriptorRef::new(this, index))
    }

    pub fn all_messages(&self) -> impl ExactSizeIterator<Item = MessageDescriptorRef<'a>> + 'a {
        MessageDescriptorRef::iter(*self)
    }

    pub fn all_enums(&self) -> impl ExactSizeIterator<Item = EnumDescriptorRef<'a>> + 'a {
        EnumDescriptorRef::iter(*self)
    }

    pub fn all_extensions(&self) -> impl ExactSizeIterator<Item = ExtensionDescriptorRef<'a>> + 'a {
        ExtensionDescriptorRef::iter(*self)
    }

    pub fn get_message_by_name(&self, name: &str) -> Option<MessageDescriptorRef<'a>> {
        MessageDescriptorRef::try_get_by_name(*self, name)
    }

    pub fn get_enum_by_name(&self, name: &str) -> Option<EnumDescriptorRef<'a>> {
        EnumDescriptorRef::try_get_by_name(*self, name)
    }
}

impl DescriptorPoolInner {
    fn build_files(
        &mut self,
        files: impl IntoIterator<Item = FileDescriptorProto>,
    ) -> Result<Range<FileIndex>, DescriptorError> {
        let start = self.files.len();

        for file in files {
            let syntax = match file.syntax.as_deref() {
                None | Some("proto2") => Syntax::Proto2,
                Some("proto3") => Syntax::Proto3,
                Some(s) => return Err(DescriptorError::unknown_syntax(s)),
            };

            match self.files.iter().find(|f| f.raw.name() == file.name()) {
                None => {
                    let index = to_index(self.files.len());
                    self.file_names.insert(file.name().into(), index);
                    self.files.push(FileDescriptorInner {
                        raw: file,
                        syntax,
                        services: Default::default(),
                    });
                }
                // Skip duplicate files only if they match exactly
                Some(existing_file) if existing_file.raw == file => continue,
                Some(_) => return Err(DescriptorError::file_already_exists(file.name())),
            }
        }

        let end = self.files.len();

        for file in &self.files[start..end] {
            for dependency in &file.raw.dependency {
                if !self.file_names.contains_key(dependency.as_str()) {
                    return Err(DescriptorError::file_not_found(file.raw.name(), dependency));
                }
            }
            for &dependency_index in &file.raw.public_dependency {
                if (dependency_index as usize) >= file.raw.dependency.len() {
                    return Err(DescriptorError::file_not_found(
                        file.raw.name(),
                        dependency_index,
                    ));
                }
            }
        }

        Ok(to_index(start)..to_index(end))
    }
}

impl fmt::Debug for DescriptorPool {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.as_ref().fmt(f)
    }
}

impl PartialEq for DescriptorPool {
    fn eq(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.inner, &other.inner)
    }
}

impl Eq for DescriptorPool {}

impl<'a> PartialEq for DescriptorPoolRef<'a> {
    fn eq(&self, other: &Self) -> bool {
        Arc::ptr_eq(self.inner, other.inner)
    }
}

impl<'a> Eq for DescriptorPoolRef<'a> {}

impl<'a> fmt::Debug for DescriptorPoolRef<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("DescriptorPool")
            // .field("files", &debug_fmt_iter(self.files()))
            // .field("services", &debug_fmt_iter(self.services()))
            // .field("all_messages", &debug_fmt_iter(self.all_messages()))
            // .field("all_enums", &debug_fmt_iter(self.all_enums()))
            // .field("all_extensions", &debug_fmt_iter(self.all_extensions()))
            .finish()
    }
}

impl FileDescriptor {
    /// Create a new [`FileDescriptor`] referencing the file at `index` within the given [`DescriptorPool`].
    ///
    /// # Panics
    ///
    /// Panics if `index` is out-of-bounds.
    pub fn new(descriptor_pool: DescriptorPool, index: usize) -> Self {
        debug_assert!(index < descriptor_pool.files().len());
        FileDescriptor {
            pool: descriptor_pool,
            index: to_index(index),
        }
    }

    /// Gets a [`FileDescriptorRef`] referencing this file.
    pub fn as_ref(&self) -> FileDescriptorRef<'_> {
        FileDescriptorRef {
            pool: self.pool.as_ref(),
            index: self.index,
        }
    }

    /// Gets a reference to the [`DescriptorPool`] this file is included in.
    pub fn parent_pool(&self) -> DescriptorPool {
        self.as_ref().parent_pool().to_owned()
    }

    /// Gets the unique name of this file relative to the root of the source tree,
    /// e.g. `path/to/my_package.proto`.
    pub fn name(&self) -> &str {
        self.as_ref().name()
    }

    /// Gets the name of the package specifier for a file, e.g. `my.package`.
    ///
    /// If no package name is set, an empty string is returned.
    pub fn package_name(&self) -> &str {
        self.as_ref().package_name()
    }

    /// Gets the index of this file within the parent [`DescriptorPool`].
    pub fn index(&self) -> usize {
        self.as_ref().index()
    }

    /// Gets the syntax of this protobuf file.
    pub fn syntax(&self) -> Syntax {
        self.as_ref().syntax()
    }

    /// Gets the public dependencies of this file.
    ///
    /// This corresponds to the [`FileDescriptorProto::public_dependency`] field.
    pub fn dependencies(&self) -> impl ExactSizeIterator<Item = FileDescriptor> + '_ {
        self.as_ref()
            .dependencies()
            .map(FileDescriptorRef::to_owned)
    }

    /// Gets the top-level message types defined within this file.
    ///
    /// This does not include nested messages defined within another message.
    pub fn messages(&self) -> impl ExactSizeIterator<Item = MessageDescriptor> + '_ {
        self.as_ref().messages().map(MessageDescriptorRef::to_owned)
    }

    /// Gets the top-level enum types defined within this file.
    ///
    /// This does not include nested enums defined within another message.
    pub fn enums(&self) -> impl ExactSizeIterator<Item = EnumDescriptor> + '_ {
        self.as_ref().enums().map(EnumDescriptorRef::to_owned)
    }

    /// Gets the top-level extension fields defined within this file.
    ///
    /// This does not include nested extensions defined within another message.
    pub fn extensions(&self) -> impl ExactSizeIterator<Item = ExtensionDescriptor> + '_ {
        self.as_ref()
            .extensions()
            .map(ExtensionDescriptorRef::to_owned)
    }

    /// Gets the services defined within this file.
    pub fn services(&self) -> impl ExactSizeIterator<Item = ServiceDescriptor> + '_ {
        self.as_ref().services().map(ServiceDescriptorRef::to_owned)
    }

    /// Gets a reference to the raw [`FileDescriptorProto`] wrapped by this [`FileDescriptor`].
    pub fn file_descriptor_proto(&self) -> &FileDescriptorProto {
        self.as_ref().file_descriptor_proto()
    }
}

impl<'a> FileDescriptorRef<'a> {
    pub fn new(descriptor_pool: DescriptorPoolRef<'a>, index: usize) -> Self {
        FileDescriptorRef {
            pool: descriptor_pool,
            index: to_index(index),
        }
    }

    pub fn to_owned(self) -> FileDescriptor {
        FileDescriptor {
            pool: self.pool.to_owned(),
            index: self.index,
        }
    }

    fn iter(
        pool: DescriptorPoolRef<'a>,
    ) -> impl ExactSizeIterator<Item = FileDescriptorRef<'a>> + 'a {
        (0..pool.inner.files.len()).map(move |index| FileDescriptorRef::new(pool, index))
    }

    pub fn parent_pool(&self) -> DescriptorPoolRef<'a> {
        self.pool
    }

    pub fn name(&self) -> &'a str {
        self.file_descriptor_proto().name()
    }

    pub fn package_name(&self) -> &'a str {
        self.file_descriptor_proto().package()
    }

    pub fn index(&self) -> usize {
        self.index as usize
    }

    pub fn syntax(&self) -> Syntax {
        self.file_inner().syntax
    }

    pub fn dependencies(&self) -> impl ExactSizeIterator<Item = FileDescriptorRef<'a>> + 'a {
        let pool = self.parent_pool();
        let raw = self.file_descriptor_proto();
        raw.public_dependency.iter().map(move |&i| {
            pool.get_file_by_name(&raw.dependency[i as usize])
                .expect("dependency not found")
        })
    }

    pub fn messages(&self) -> impl ExactSizeIterator<Item = MessageDescriptorRef<'a>> + 'a {
        let pool = self.parent_pool();
        let raw_file = self.file_descriptor_proto();
        raw_file.message_type.iter().map(move |raw_message| {
            pool.get_message_by_name(&make_full_name(raw_file.package(), raw_message.name()))
                .expect("message not found")
        })
    }

    pub fn enums(&self) -> impl ExactSizeIterator<Item = EnumDescriptorRef<'a>> + 'a {
        let pool = self.parent_pool();
        let raw_file = self.file_descriptor_proto();
        raw_file.enum_type.iter().map(move |raw_enum| {
            pool.get_enum_by_name(&make_full_name(raw_file.package(), raw_enum.name()))
                .expect("enum not found")
        })
    }

    pub fn extensions(&self) -> impl ExactSizeIterator<Item = ExtensionDescriptorRef<'a>> + 'a {
        let pool = self.parent_pool();
        let raw_file = self.file_descriptor_proto();
        raw_file.extension.iter().map(move |raw_extension| {
            let extendee = pool
                .inner
                .type_map
                .resolve_type_name(raw_file.package(), raw_extension.extendee())
                .expect("extendee not found");
            MessageDescriptorRef::new(pool, extendee)
                .get_extension(raw_extension.number() as u32)
                .expect("extension not found")
        })
    }

    pub fn services(&self) -> impl ExactSizeIterator<Item = ServiceDescriptorRef<'a>> + 'a {
        let pool = self.parent_pool();
        self.file_inner()
            .services
            .clone()
            .map(move |index| ServiceDescriptorRef::new(pool, index as usize))
    }

    pub fn file_descriptor_proto(&self) -> &'a FileDescriptorProto {
        &self.file_inner().raw
    }

    fn file_inner(&self) -> &'a FileDescriptorInner {
        &self.pool.inner.files[self.index as usize]
    }
}

impl<'a> fmt::Debug for FileDescriptorRef<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("FileDescriptor")
            .field("name", &self.name())
            .field("package_name", &self.package_name())
            .finish()
    }
}

impl fmt::Debug for FileDescriptor {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.as_ref().fmt(f)
    }
}

impl fmt::Debug for Syntax {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            Syntax::Proto2 => write!(f, "proto2"),
            Syntax::Proto3 => write!(f, "proto3"),
        }
    }
}

fn make_full_name(namespace: &str, name: &str) -> Box<str> {
    let namespace = namespace.trim_start_matches('.');
    if namespace.is_empty() {
        name.into()
    } else {
        let mut full_name = String::with_capacity(namespace.len() + 1 + name.len());
        full_name.push_str(namespace);
        full_name.push('.');
        full_name.push_str(name);
        full_name.into_boxed_str()
    }
}

fn parse_namespace(full_name: &str) -> &str {
    match full_name.rsplit_once('.') {
        Some((namespace, _)) => namespace,
        None => "",
    }
}

fn parse_name(full_name: &str) -> &str {
    match full_name.rsplit_once('.') {
        Some((_, name)) => name,
        None => full_name,
    }
}

macro_rules! impl_from_for_ref {
    ($owned:ty => $ref:ident) => {
        impl<'a> From<&'a $owned> for $ref<'a> {
            fn from(value: &'a $owned) -> Self {
                value.as_ref()
            }
        }

        impl<'a> From<$ref<'a>> for $owned {
            fn from(value: $ref<'a>) -> Self {
                value.to_owned()
            }
        }
    };
}

impl_from_for_ref!(DescriptorPool => DescriptorPoolRef);
impl_from_for_ref!(FileDescriptor => FileDescriptorRef);
impl_from_for_ref!(ServiceDescriptor => ServiceDescriptorRef);
impl_from_for_ref!(MethodDescriptor => MethodDescriptorRef);
impl_from_for_ref!(MessageDescriptor => MessageDescriptorRef);
impl_from_for_ref!(FieldDescriptor => FieldDescriptorRef);
impl_from_for_ref!(ExtensionDescriptor => ExtensionDescriptorRef);
impl_from_for_ref!(EnumDescriptor => EnumDescriptorRef);
impl_from_for_ref!(EnumValueDescriptor => EnumValueDescriptorRef);
impl_from_for_ref!(OneofDescriptor => OneofDescriptorRef);
impl_from_for_ref!(Kind => KindRef);

fn debug_fmt_iter<I>(i: I) -> impl fmt::Debug
where
    I: Iterator,
    I::Item: fmt::Debug,
{
    struct Wrapper<T>(Vec<T>);

    impl<T> fmt::Debug for Wrapper<T>
    where
        T: fmt::Debug,
    {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_list().entries(&self.0).finish()
        }
    }

    Wrapper(i.collect())
}

fn to_index(i: usize) -> u32 {
    i.try_into().expect("index too large")
}

#[test]
fn assert_descriptor_send_sync() {
    fn foo<T: Send + Sync>() {}

    foo::<DescriptorPool>();
}
